# Generated by Django 4.2.6 on 2023-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_publiction_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(default='2023-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
