# Generated by Django 4.2.3 on 2023-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_publication_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='isPrivate',
            new_name='prive',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='picture',
        ),
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
