# Generated by Django 3.2.20 on 2023-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('TESTEUR', 'TESTEUR'), ('PLAYER', 'PLAYER')], default='PLAYER', max_length=30, verbose_name='rôle'),
        ),
    ]
