# Generated by Django 3.2.20 on 2023-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_auto_20230726_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveBigIntegerField(default=3),
        ),
    ]
